# Hotel Facilito

## ¿Quién va a cancelar?

*Hotel Facilito* se está preparando para las vacaciones de verano, sin embargo, les preocupa que muchos de sus clientes cancelan de ultima hora, dejándoles con habitaciones vacías – sucede que algunos clientes simplemente no se presentan y, a pesar de que a veces se cobra una cuota de reservación, la gran mayoría de las ganancias se obtiene cuando los huéspedes pagan el resto al ocupar la habitación. 

Usando sus datos, les gustaría que les ayudaras a identificar a aquellos clientes que tienen más posibilidad de cancelar ya que les gustaría darles seguimiento para que si en caso de que requieran cancelar, se haga con la mayor antelación posible.

![](./header.png)

## Datos

*Hoteles Facilito* tiene dos sucursales, uno ubicado en la capital del estado, "City Hotel" y otro en una comunidad cercana a la costa, "Resort Hotel".

Los datos que te ha enviado están en formato CSV, en donde cada línea representa una reservación con los siguientes atributos:

  - `hotel`: Hotel en el que se hizo la reserva.
  - `is_canceled`: Indica si la reserva fue cancelada o no.
  - `lead_time`: Número de días que transcurrieron entre la fecha de ingreso de la reserva en el PMS y la fecha de llegada.
  - `arrival_date_year`: Año de la fecha de llegada.
  - `arrival_date_month`: Mes de la fecha de llegada con 12 categorías: "Enero" a "Diciembre".
  - `arrival_date_week_number`: Número de semana de la fecha de llegada.
  - `arrival_date_day_of_month`: Día del mes de la fecha de llegada.
  - `stays_in_weekend_nights`: Número de noches de fin de semana (sábado o domingo) que el huésped se quedó o reservó para quedarse en el hotel.
  - `stays_in_week_nights`: Número de noches de semana (lunes a viernes) que el huésped se quedó o reservó para quedarse en el hotel.
  - `adults`: Número de adultos.
  - `children`: Número de niños.
  - `babies`: Número de bebés.
  - `meal`: Tipo de comida reservada. Valor categórico.
  - `country`: País de origen. Las categorías se representan según ISO 3155–3:2013.
  - `market_segment`: Designación del segmento de mercado.
  - `distribution_channel`: Canal de distribución de la reserva.
  - `is_repeated_guest`: Valor que indica si el nombre de la reserva era de un huésped recurrente (1) o no (0).
  - `previous_cancellations`: Número de reservas anteriores que fueron canceladas por el cliente antes de la reserva actual.
  - `previous_bookings_not_canceled`: Número de reservas anteriores que no fueron canceladas por el cliente antes de la reserva actual.
  - `reserved_room_type`: Código del tipo de habitación reservada. El código se presenta en lugar de la designación por razones de anonimato.
  - `assigned_room_type`: Código del tipo de habitación asignada a la reserva. A veces, el tipo de habitación asignada difiere del tipo de habitación reservada debido a razones operativas del hotel (por ejemplo, sobreventa) o por solicitud del cliente. El código se presenta en lugar de la designación por razones de anonimato.
  - `booking_changes`: Número de cambios/modificaciones realizados a la reserva desde el momento en que se ingresó en el PMS hasta el momento del check-in o la cancelación.
  - `deposit_type`: Indicación de si el cliente hizo un depósito para garantizar la reserva.
  - `agent`: ID de la agencia de viajes que realizó la reserva.
  - `company`: ID de la empresa/entidad que realizó la reserva o es responsable de pagar la reserva.
  - `days_in_waiting_list`: Número de días que la reserva estuvo en lista de espera antes de ser confirmada al cliente.
  - `customer_type`: Tipo de reserva.
  - `adr`: Tarifa diaria promedio.
  - `required_car_parking_spaces`: Número de espacios de estacionamiento requeridos por el cliente.
  - `total_of_special_requests`: Número de solicitudes especiales realizadas por el cliente (por ejemplo, cama doble o piso alto).
  - `reservation_status`: Último estado de la reserva.
  - `reservation_status_date`: Fecha en que se estableció el último estado.
  - `name`: Nombre del cliente.
  - `email`: Correo electrónico del cliente.
  - `phone`: Teléfono del cliente.
  - `credit_card`: Últimos cuatro dígitos de la tarjeta de crédito del cliente.

Los datos que te ha enviado la compañía están en el archivo `hotel_bookings_training.csv`.

> En realidad los datos provienen de [este dataset de Kaggle](https://www.kaggle.com/datasets/mojtaba142/hotel-booking), y puedes consultar más sobre el origen de los datos [en esta publicación](https://www.sciencedirect.com/science/article/pii/S2352340918315191)

## ¿Qué métricas podemos medir? 

¿Accuracy? pero, y ¿si nos interesa otra cosa?

Nos interesa hallar a TODAS las personas que potencialmente pueden cancelar, y la verdad es que a nuestros clientes no les molesta mucho si les llamamos para confirmar su reserva.

## Ejercicio

1) La variable que tratamos de predecir es 'is_canceled' 
2) La respuesta que vamos a obtener es binaria - (Aprendizaje supervisado - Clasificación - Clasificación binaria (sí - no))
3) ¿Cuál es la  métrica que vamos a utilizar o qué metricas podemos medir ?   
   -  Una métrica es un número que nos permite medir el rendimiento del modelo comparando:   
    lo que el modelo predijo   
    vs.   
    lo que realmente ocurrió.   
    Por ejemplo, conceptualmente:   
    
    - Métrica	¿Qué mide? : 
    Accuracy	Qué porcentaje de predicciones fueron correctas   
    Precision	De las reservas que el modelo predijo como canceladas, cuántas realmente fueron canceladas   
    Recall	De todas las reservas que realmente fueron canceladas, cuántas detectó el modelo   
    F1-score	Combina Precision y Recall   
    ROC-AUC	Qué tan bien distingue el modelo entre las dos clases   
    Confusion Matrix	Muestra los aciertos y errores separados por clase   
    Log Loss	Evalúa la calidad de las probabilidades que produce el modelo

In [18]:
import pandas as pd

In [19]:
hotel_bookings = pd.read_csv("hotel_bookings_training.csv")

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
hotel_bookings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119190 entries, 0 to 119189
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119190 non-null  object
 1   is_canceled                     119190 non-null  int64
 2   lead_time                       119190 non-null  int64
 3   arrival_date_year               119190 non-null  int64
 4   arrival_date_month              119190 non-null  object
 5   arrival_date_week_number        119190 non-null  int64
 6   arrival_date_day_of_month       119190 non-null  int64
 7   stays_in_weekend_nights         119190 non-null  int64
 8   stays_in_week_nights            119190 non-null  int64
 9   adults                          119190 non-null  int64
 10  children                        119186 non-null  float64
 11  babies                          119190 non-null  int64
 12  meal                            119190 non-null  object
 13  country                         118703 non-null  object
 14  market_segment                  119190 non-null  object
 15  distribution_channel            119190 non-null  object
 16  is_repeated_guest               119190 non-null  int64
 17  previous_cancellations          119190 non-null  int64
 18  previous_bookings_not_canceled  119190 non-null  int64
 19  reserved_room_type              119190 non-null  object
 20  assigned_room_type              119190 non-null  object
 21  booking_changes                 119190 non-null  int64
 22  deposit_type                    119190 non-null  object
 23  agent                           102875 non-null  float64
 24  company                         6788 non-null    float64
 25  days_in_waiting_list            119190 non-null  int64
 26  customer_type                   119190 non-null  object
 27  adr                             119190 non-null  float64
 28  required_car_parking_spaces     119190 non-null  int64
 29  total_of_special_requests       119190 non-null  int64
 30  reservation_status              119190 non-null  object
 31  reservation_status_date         119190 non-null  object
 32  name                            119190 non-null  object
 33  email                           119190 non-null  object
 34  phone-number                    119190 non-null  object
 35  credit_card                     119190 non-null  object
dtypes: float64(4), int64(16), object(16)
memory usage: 32.7+ MB

### Sobre los datos personales...

Nos deshacemos de los datos personales – que además carecen de utilidad por ser únicos:

In [20]:
hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,City Hotel,0,21,2015,September,36,1,0,4,2,...,Transient,105.0,0,0,Check-Out,2015-09-05,Timothy George,George_Timothy@mail.com,638-082-2623,************3627
1,City Hotel,0,20,2016,September,38,12,1,0,1,...,Transient,89.0,0,2,Check-Out,2016-09-13,Angela Carpenter,Angela.C@verizon.com,874-747-0095,************7934
2,City Hotel,0,2,2016,March,13,24,0,2,2,...,Transient,134.0,0,1,Check-Out,2016-03-26,Richard Scott,RScott80@verizon.com,311-116-4410,************1822
3,Resort Hotel,1,6,2016,April,17,21,0,1,2,...,Transient,73.0,0,0,Canceled,2016-04-18,Daniel Cooper,DanielCooper@yandex.com,375-297-1783,************7716
4,Resort Hotel,0,40,2015,August,34,20,2,3,2,...,Transient,176.8,1,1,Check-Out,2015-08-25,David Young,David_Young@gmail.com,910-698-3037,************4952

Hay información que no es útil, por ejemplo, número de tarjeta de crédito, correo, número de teléfono, etc. Por lo tanto, vamos a eliminar algunas columnas que no son útiles para nuestro análisis.

In [11]:
# Remove personal information of customers
hotel_bookings = hotel_bookings.drop(['name', 'email', 'phone-number', 'credit_card'], axis=1)

In [12]:
hotel_bookings.sample(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
6546,Resort Hotel,1,312,2017,March,10,5,2,5,2,...,No Deposit,298.0,NaN,0,Transient-Party,30.0,0,0,Canceled,2016-09-15
116897,City Hotel,1,37,2016,October,42,13,0,3,2,...,No Deposit,56.0,NaN,0,Transient-Party,105.0,0,0,Canceled,2016-09-06
25775,Resort Hotel,1,228,2016,September,37,10,2,2,2,...,No Deposit,96.0,NaN,0,Transient,61.2,0,0,Canceled,2016-02-01
23633,City Hotel,0,58,2016,March,14,31,0,3,2,...,No Deposit,9.0,NaN,0,Transient-Party,90.9,0,1,Check-Out,2016-04-03
84157,City Hotel,1,54,2017,March,11,15,0,2,1,...,No Deposit,94.0,NaN,0,Transient-Party,65.0,0,1,No-Show,2017-03-15
16564,City Hotel,0,6,2017,January,4,22,1,0,2,...,No Deposit,9.0,NaN,0,Transient,88.0,0,0,Check-Out,2017-01-23
34225,Resort Hotel,0,58,2017,April,15,12,0,1,2,...,No Deposit,251.0,NaN,0,Transient-Party,80.0,0,2,Check-Out,2017-04-13
7138,Resort Hotel,1,9,2016,July,28,6,0,1,1,...,No Deposit,146.0,NaN,0,Transient,65.0,0,0,Canceled,2016-07-05
5071,City Hotel,1,176,2016,April,15,9,1,1,2,...,Non Refund,21.0,NaN,0,Transient,125.0,0,0,Canceled,2015-11-23
14318,City Hotel,0,9,2016,May,23,31,0,1,2,...,No Deposit,9.0,NaN,0,Transient,131.0,0,2,Check-Out,2016-06-01

## EDA

In [21]:
from ydata_profiling import ProfileReport

C:\Users\Edison\AppData\Local\Temp\ipykernel_19852\44057814.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [23]:
profile = ProfileReport(hotel_bookings, title="Pandas Profiling Report")

In [9]:
# profile.to_file("bookings_profile.html")
## file:///Users/antonio.feregrino/hub/cf-ml/hotel-facilito/bookings_profile.html

In [24]:
profile.to_file("bookings_profile.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 36/36 [00:05<00:00,  6.14it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

'Reservation_status' tiene alta correlación con 'is_canceled', ambas variables son lo mismo, si dejamos reservation_status , estariamos incurriendo  en lo que se lalma filtracion de datos   
¿Qué representa cada una?
En este dataset:
- is_canceled → indica si la reserva terminó cancelada: 0 o 1.   
- reservation_status → indica el estado final de la reserva: Canceled, Check-Out o No-Show.  

La razón más importante es:   
reservation_status contiene información que solo se conoce después de que el resultado de la reserva se ha producido.   

Eso es data leakage.  
El artículo original del dataset describe reservation_status como el último estado de la reserva y reservation_status_date como la fecha en que se estableció ese último estado. PubMed Central (PMC)

## Data leakage

La variable `reservation_status` indica el estado de la reservación, esta es en realidad un reflejo de `is_canceled`, si la dejamos dentro de las variables de entrada estamos filtrando información al modelo. Este nos dará un resultado excelente, pero en realidad no nos servirá de nada en la vida real. Debemos sacarla del dataset junto con otras varaibles asociadas:

In [25]:
# Avoid data leakage
hotel_bookings = hotel_bookings.drop(['reservation_status', 'reservation_status_date'], axis=1)

## Separa la variable a predecir
Vamos a separar la variable objetivo del data set

In [26]:
is_canceled = hotel_bookings['is_canceled'].copy()
hotel_data = hotel_bookings.drop(['is_canceled'], axis=1)

'is_canceled'
Esta será tu variable objetivo, también llamada:    
- target    
- variable dependiente   
- variable a predecir   
- normalmente 'y'

In [27]:
is_canceled.value_counts()

is_canceled
0    75039
1    44151
Name: count, dtype: int64

In [28]:
is_canceled

0         0
1         0
2         0
3         1
4         0
         ..
119185    0
119186    0
119187    0
119188    0
119189    0
Name: is_canceled, Length: 119190, dtype: int64

In [29]:
hotel_data

,hotel,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,name,email,phone-number,credit_card
0,City Hotel,21,2015,September,36,1,0,4,2,0.0,...,NaN,0,Transient,105.0,0,0,Timothy George,George_Timothy@mail.com,638-082-2623,************3627
1,City Hotel,20,2016,September,38,12,1,0,1,0.0,...,NaN,0,Transient,89.0,0,2,Angela Carpenter,Angela.C@verizon.com,874-747-0095,************7934
2,City Hotel,2,2016,March,13,24,0,2,2,0.0,...,NaN,0,Transient,134.0,0,1,Richard Scott,RScott80@verizon.com,311-116-4410,************1822
3,Resort Hotel,6,2016,April,17,21,0,1,2,0.0,...,NaN,0,Transient,73.0,0,0,Daniel Cooper,DanielCooper@yandex.com,375-297-1783,************7716
4,Resort Hotel,40,2015,August,34,20,2,3,2,0.0,...,NaN,0,Transient,176.8,1,1,David Young,David_Young@gmail.com,910-698-3037,************4952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119185,Resort Hotel,1,2016,June,26,21,0,1,1,0.0,...,NaN,0,Transient,79.0,0,0,Ruben Bush,Ruben_B@att.com,331-185-9637,************9981
119186,Resort Hotel,17,2016,October,45,30,1,0,2,0.0,...,346.0,0,Transient-Party,66.0,1,0,Benjamin Pham,Benjamin_P@hotmail.com,825-033-4937,************4217
119187,City Hotel,1,2017,April,17,27,0,1,2,0.0,...,NaN,0,Transient,160.0,0,0,Emily Gonzales,EmilyGonzales@hotmail.com,454-605-7099,************5639
119188,Resort Hotel,10,2017,June,25,24,2,1,3,0.0,...,NaN,0,Transient,185.0,1,0,Jeremy Chapman,JChapman@zoho.com,835-084-0765,************5263
119189,Resort Hotel,56,2015,November,48,23,0,0,2,0.0,...,NaN,0,Transient,0.0,0,1,Elijah Bradford,Elijah_B@protonmail.com,472-118-9806,************8257

## Split dataset

El objetivo de dividir los datos es para que entrenen un mejor modelo, porq si mas tiempo tarde en dividir los datos, más informacion se va a ir filtrando en su desarrollo del modelo, ya que tenemos cerca de 120 000 datos si nos va a dar oportunidad de tener un conjunto de datos, de prueba y de validacion.

Y la idea de separar los datos antes de entrenar el modelo es precisamente para evitar que información del conjunto de prueba/validación influya en el entrenamiento.

In [32]:
# Calculate test and validation set size:
original_count = len(hotel_bookings)  #Cuenta el número de registros en el dataset 
training_size = 0.60 # 60% de los datos se utilizarán para entrenamiento
test_size = (1 - training_size) / 2    # 20% de los datos se utilizarán para prueba
training_count = int(original_count * training_size) # Calcula el número de registros para el conjunto de entrenamiento
test_count = int(original_count * test_size) # Calcula el número de registros para el conjunto de prueba
validation_count = original_count - training_count - test_count # Calcula el número de registros para el conjunto de validación

print(training_count, test_count, validation_count)

71514 23838 23838

TRAINING → desarrollar modelo    
VALIDATION → ajustar/elegir   
TEST → evaluación final   

             120 000     
                │
       ┌────────┼────────┐   
       ↓        ↓        ↓    
      60%      20%      20%   
    Training Validation  Test   
       │         │        │   
       ↓         ↓        ↓    
    aprende    ajusta   FINAL

no garantiza por sí mismo que no exista leakage, todavía puedes tener leakage dentro de training.   
or ejemplo, si hotel_data todavía contiene:    
reservation_status    
reservation_status_date

In [34]:
from sklearn.model_selection import train_test_split

train_x, rest_x, train_y, rest_y = train_test_split(hotel_data, is_canceled, train_size=training_count)
test_x, validate_x, test_y, validate_y = train_test_split(rest_x, rest_y, train_size=test_count)

print(len(train_x), len(test_x), len(validate_x))

71514 23838 23838

In [37]:
validate_x

,hotel,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,name,email,phone-number,credit_card
73333,City Hotel,68,2016,March,11,10,1,3,2,0.0,...,NaN,0,Transient,73.95,0,0,Tammy Sanchez,Tammy_Sanchez65@gmail.com,347-805-5323,************1626
7128,City Hotel,109,2016,February,9,21,2,1,2,0.0,...,NaN,44,Transient,75.00,0,0,Brandi Craig,BCraig29@yandex.com,876-366-6036,************7591
110164,City Hotel,149,2017,April,13,1,2,1,2,0.0,...,NaN,0,Transient,99.00,0,0,Brian Velez,Velez_Brian@outlook.com,856-884-5548,************3476
66535,Resort Hotel,343,2017,June,24,16,1,2,2,0.0,...,NaN,0,Transient,70.20,0,0,Rebecca Davis,Davis_Rebecca@comcast.net,539-049-9054,************1320
109274,City Hotel,45,2016,February,9,25,0,3,2,0.0,...,NaN,0,Transient,80.30,0,1,Jessica Woods,JWoods@outlook.com,947-262-1337,************3862
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33163,Resort Hotel,51,2017,June,26,30,3,7,2,0.0,...,NaN,0,Transient,93.00,0,0,Ryan Sexton,Ryan_S@gmail.com,286-024-5043,************1477
97049,City Hotel,44,2016,March,11,10,2,3,2,0.0,...,NaN,0,Transient,80.26,0,1,Andrew Fisher,Andrew_F@zoho.com,670-200-3083,************9973
17203,Resort Hotel,14,2015,December,52,26,0,1,2,0.0,...,NaN,0,Transient,65.00,0,2,April Bowers,Bowers_April@att.com,197-952-7462,************7783
59874,City Hotel,96,2017,June,25,21,0,1,2,1.0,...,NaN,0,Transient,162.00,0,2,Jacob Brooks,JacobBrooks19@aol.com,988-297-1908,************4258
24030,Resort Hotel,17,2015,July,29,16,0,3,2,0.0,...,NaN,0,Transient,151.33,0,0,Douglas Griffin,Douglas_G@yahoo.com,274-198-6087,************8596

In [45]:
validate_x.value_counts('arrival_date_month')

arrival_date_month
August       2739
July         2577
May          2369
October      2231
April        2208
June         2147
September    2093
March        1931
February     1602
December     1396
November     1360
January      1185
Name: count, dtype: int64

## Variables a codificar - One-hot encoding

 - hotel, meal, distribution_channel, reserved_room_type, assigned_room_type, customer_type, deposit_type

Un modelo de machine learning no puede trabajar directamente con cadena , todo tiene que ser número, tratamos de convertir la columna a numero, con la tecnica on hot encoding, lo convierte en 2 columnas binarias, 0 y 1

In [46]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
one_hot_encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")  #no quiero que mi salida sea dispersa, quiero que sea un array normal. handle_unknown="ignore" para que ignore las categorías desconocidas
#Estás creando un objeto que sabe cómo transformar categorías en columnas binarias.

In [49]:
one_hot_encoder.fit(train_x[['hotel']])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [ ]:
one_hot_encoder.transform(train_x[['hotel']])

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

Número de columnas One-Hot = número de categorías aprendidas, salvo configuraciones especiales como drop.   

Y en tu caso hotel tiene dos categorías, por eso aparecen dos columnas binarias.

| hotel | City Hotel | Resort Hotel |   

| City Hotel | 1 | 0 |   
| Resort Hotel | 0 | 1 |   
| City Hotel | 1 | 0 |

Probemos con otra variable distribution:chanel

In [51]:
one_hot_encoder.fit(train_x[['distribution_channel']])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [60]:
hotel_bookings.value_counts('distribution_channel')

distribution_channel
TA/TO        97706
Direct       14616
Corporate     6670
GDS            193
Undefined        5
Name: count, dtype: int64

In [53]:
one_hot_encoder.transform(train_x[['distribution_channel']])

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.]])

2 categorías → 2 columnas   
3 categorías → 3 columnas   
10 categorías → 10 columnas   
100 categorías → 100 columnas   

¿Qué hacemos con variables categóricas que tienen cientos o miles de categorías?   

Ahí ya entran estrategias como One-Hot Encoding, agrupación de categorías poco frecuentes, Target Encoding, Frequency Encoding, etc.

## Variables a binarizar

 - total_of_special_requests, required_car_parking_spaces, booking_changes, previous_bookings_not_canceled, previous_cancellations

In [63]:
from sklearn.preprocessing import Binarizer

Binarizer convierte una variable numérica en una variable de dos estados: 0 y 1, utilizando un umbral (threshold).   
valor ≤ threshold  → 0   
valor > threshold  → 1

El Binarizer se utiliza cuando tienes una variable numérica y quieres transformarla en una variable binaria.

Diferencia con lo que acabamos de estudiar   
Técnica	      |  Entrada	   |  Salida	          |    Objetivo   
```OneHotEncoder``` 	```Categórica```	    ```Varias columnas 0/1```	   ```Representar categorías```   
Binarizer	    Numérica	    Una variable 0/1	   Crear una condición mediante umbral   
StandardScaler	Numérica	    Numérica escalada	   Cambiar la escala   
MinMaxScaler	Numérica	    Numérica escalada	   Llevar a un rango

In [64]:
binarizer = Binarizer()

In [98]:
b1= train_x[['total_of_special_requests']].sample(10)  #vemos los tipos de datos que tiene la columna total_of_special_requests en este caso valores 0,1,2,3,4
b1

        total_of_special_requests
16598                           0
114308                          0
105960                          1
73087                           0
56562                           0
60200                           2
33534                           3
117175                          1
70467                           0
115629                          0

In [99]:
binarizer.fit(b1[['total_of_special_requests']])

Binarizer()

In [100]:
binarizer.transform(b1[['total_of_special_requests']])

array([[0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0]], dtype=int64)

In [101]:
#Ahora vamos a comparar el resultado de la binarizacion y el los datos train_x para identificar como se comporta la binarizacion con los datos de entrenamiento.
b1['res']=binarizer.transform(b1[['total_of_special_requests']])
b1

        total_of_special_requests  res
16598                           0    0
114308                          0    0
105960                          1    1
73087                           0    0
56562                           0    0
60200                           2    1
33534                           3    1
117175                          1    1
70467                           0    0
115629                          0    0

El objetivo es crear una neuva variable `has_made_special_requests`

In [ ]:

_ = train_x.copy()
binarizer.fit(_[['total_of_special_requests']])
_['has_made_special_requests'] = binarizer.transform(train_x[['total_of_special_requests']])

_[['total_of_special_requests', 'has_made_special_requests']].sample(10)

        total_of_special_requests  has_made_special_requests
47391                           1                          1
111874                          0                          0
66996                           1                          1
47074                           0                          0
14996                           0                          0
81377                           0                          0
77693                           0                          0
1673                            0                          0
19220                           1                          1
87664                           0                          0

## Variables a escalar

 - adr

In [20]:
from sklearn.preprocessing import RobustScaler

In [21]:
scaler = RobustScaler()

In [22]:
_ = train_x.copy()
scaler.fit(_[['adr']])
_['adr_scaled'] = scaler.transform(train_x[['adr']])

_[['adr', 'adr_scaled']].sample(10)

           adr  adr_scaled
77403   136.00    0.728070
17884   128.00    0.587719
10509    62.80   -0.556140
40555   111.92    0.305614
56880   177.50    1.456140
25399   288.03    3.395263
118718   34.00   -1.061404
86244    52.00   -0.745614
63141    75.00   -0.342105
33587    88.40   -0.107018

## Variables a dejar como tal

 - stays_in_weekend_nights, stays_in_week_nights
 
 
 > El tratamiento de estas depende del modelo a usar

## Armando un pipeline de transformación

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import FeatureUnion, Pipeline

In [24]:
one_hot_encoding = ColumnTransformer([
    (
        'one_hot_encode',
        OneHotEncoder(sparse_output=False, handle_unknown="ignore"),
        [
            "hotel",
            "meal", 
            "distribution_channel", 
            "reserved_room_type", 
            "assigned_room_type", 
            "customer_type"
        ]
    )
])

In [25]:
binarizer = ColumnTransformer([
    (
        'binarizer',
        Binarizer(),
        [
            "total_of_special_requests", 
            "required_car_parking_spaces", 
            "booking_changes", 
            "previous_bookings_not_canceled", 
            "previous_cancellations",
        ]
    )
])
    
one_hot_binarized = Pipeline([
    ("binarizer", binarizer),
    ("one_hot_encoder", OneHotEncoder(sparse_output=False, handle_unknown="ignore")),
])

In [26]:
scaler = ColumnTransformer([
    ("scaler", RobustScaler(), ["adr"])
])

In [27]:
passthrough = ColumnTransformer([
    (
        "passthrough",
        "passthrough",
        [
            "stays_in_week_nights",
            "stays_in_weekend_nights",
        ]
    )
])

In [28]:
feature_engineering_pipeline = pipe = Pipeline(
    [
        (
            "features",
            FeatureUnion(
                [
                    ("categorical", one_hot_encoding),
                    ("categorical_binarized", one_hot_binarized),
                    ("scaled", scaler),
                    ("pass", passthrough),
                ]
            ),
        )
    ]
)

In [29]:
transformed = feature_engineering_pipeline.fit_transform(train_x)
transformed.shape

(71514, 50)

In [30]:
transformed

array([[ 0.        ,  1.        ,  0.        , ..., -0.64035088,
         2.        ,  2.        ],
       [ 0.        ,  1.        ,  0.        , ..., -0.85087719,
         3.        ,  0.        ],
       [ 1.        ,  0.        ,  1.        , ..., -0.57017544,
         1.        ,  1.        ],
       ...,
       [ 1.        ,  0.        ,  1.        , ...,  0.50526316,
         3.        ,  2.        ],
       [ 1.        ,  0.        ,  0.        , ..., -0.69807018,
         2.        ,  2.        ],
       [ 1.        ,  0.        ,  1.        , ...,  0.68350877,
         5.        ,  2.        ]])

## Model training

In [31]:
# Get a fresh copy of the pipeline
from sklearn.base import clone

feature_transformer = clone(feature_engineering_pipeline)

features_train_x = feature_transformer.fit_transform(train_x)
features_validate_x = feature_transformer.transform(validate_x)

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC

model = RandomForestClassifier(n_estimators=100)

model.fit(features_train_x, train_y)

RandomForestClassifier()

## Model validation

In [33]:
from sklearn.metrics import accuracy_score, recall_score

pred_y = model.predict(features_validate_x)

print(accuracy_score(validate_y, pred_y))
print(recall_score(validate_y, pred_y))

0.8088346337780015
0.7133807512780618

## Construcción del pipeline final

In [34]:
final_inference_pipeline = Pipeline([
    ("feature_engineering", clone(feature_engineering_pipeline)),
    ("model", RandomForestClassifier(n_estimators=100))
])

In [35]:
final_training_dataset = pd.concat([train_x, validate_x])
final_training_response = pd.concat([train_y, validate_y])

In [ ]:
final_inference_pipeline.fit(final_training_dataset, final_training_response)

## Model testing

In [ ]:
test_pred_y = final_inference_pipeline.predict(test_x)

print(accuracy_score(test_pred_y, test_y))
print(recall_score(test_pred_y, test_y))

## Model persistence

In [ ]:
from joblib import dump

dump(final_inference_pipeline, "inference_pipeline.joblib")

## Y entonces... ¿a quién le hablamos?

In [ ]:
from joblib import load

ultimate_inference_pipeline = load("inference_pipeline.joblib")

In [ ]:
new_customers = pd.read_csv("new_customers.csv")
new_customers.head()

In [ ]:
new_customers['will_cancel'] = ultimate_inference_pipeline.predict(new_customers)
new_customers[['proba_check_in', 'proba_cancel']] = ultimate_inference_pipeline.predict_proba(new_customers)

In [ ]:
new_customers[['name', 'phone-number', 'will_cancel', 'proba_cancel']].sort_values(by='proba_cancel', ascending=False).head(20)

## De tarea...

 - Entrena un modelo con *data leakage* y ve si es sospechosamente bueno
 - ¿Qué pasa si el cliente no recibió la habitación que solicitó? (`reserved_room_type` vs `assigned_room_type`)
 - No consideramos las fechas en las que iba a quedarse, ¿y si las incluyes en tu modelo?
 - ¿Podemos usar validación cruzada? 
 - ¿Qué tal de la búsqueda de hiper parámetros?